import 'package:flutter/material.dart';

void main()
{
  runApp(MaterialApp(
    debugShowCheckedModeBanner: false,
        home: Scaffold(
      appBar: AppBar(
      centerTitle: true,
        backgroundColor: Colors.red,
        title: const Text("Red and White",style: TextStyle(
          fontSize: 30,
          fontWeight: FontWeight.bold,
          color: Colors.white,
        ),
        ),
      ),
          backgroundColor: Colors.black,
          body: Center(
            child: Text.rich(
              TextSpan(
                children: [
                  TextSpan(text: ("\t\t\t\t\t\t\t\t\t\t\t G"),
                  style: TextStyle(fontWeight: FontWeight.bold,fontSize: 25,color: Colors.green),
                  ),
                  TextSpan(text: ("R"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 40,color: Colors.red),
                  ),
                  TextSpan(text: ("APHICS\n"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 25,color: Colors.green),
                  ),
                  TextSpan(text: ("\t\t\t FLUTT"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 25,color: Colors.blue),
                  ),
                  TextSpan(text: ("E"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 40,color: Colors.red),
                  ),
                  TextSpan(text: ("R\n"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 25,color: Colors.blue),
                  ),
                  TextSpan(text: ("\t\t\t\t\t\t\t\t\tAN"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 25,color: Colors.green),
                  ),
                  TextSpan(text: ("D"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 40,color: Colors.red),
                  ),
                  TextSpan(text: ("ROID"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 25,color: Colors.green),
                  ),
                  TextSpan(text: ("DESIGN\n"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 25,color: Colors.green),
                  ),
                  TextSpan(text: ("\t\t\t\t\t\t\t\t\t& "),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 40,color: Colors.red),
                  ),
                  TextSpan(text: ("DEVLOP\n"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 25,color: Colors.green),
                  ),
                  TextSpan(text: ("\t\t\t\t\t\t\t\t\tW"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 40,color: Colors.red),
                  ),
                  TextSpan(text: ("EB\n"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 25,color: Colors.blue),
                  ),
                  TextSpan(text: ("\t\t\t\t\t\t\t\t\tFAS"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 25,color: Colors.green),
                  ),
                  TextSpan(text: ("H"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 40,color: Colors.red),
                  ),
                  TextSpan(text: ("ION\n"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 25,color: Colors.green),
                  ),
                  TextSpan(text: ("\t\t\t\tANIMAT"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 25,color: Colors.green),
                  ),
                  TextSpan(text: ("I"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 40,color: Colors.red),
                  ),
                  TextSpan(text: ("ON\n"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 25,color: Colors.green),
                  ),
                  TextSpan(text: ("\t\t\t\t\t\t\t\tI"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 40,color: Colors.lightBlue),
                  ),
                  TextSpan(text: ("T"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 40,color: Colors.red),
                  ),
                  TextSpan(text: ("A-CS+\n"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 40,color: Colors.blue),
                  ),
                  TextSpan(text: ("\t\t\tGAM"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 40,color: Color.fromRGBO(215, 172, 30, 1),),
                  ),
                  TextSpan(text: ("E"),
                    style: TextStyle(fontWeight: FontWeight.bold,fontSize: 40,color: Colors.red),
                  ),
                ],
              ),
            ),
          ),
    ),
  ),
  );
}